// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXmGLV9OkKNl4pMxIcNoxMNqsK0zk_4TU',
    appId: '1:1054392847654:web:1e2c65f4da0cd33e9285e7',
    messagingSenderId: '1054392847654',
    projectId: 'personal-note-2b218',
    authDomain: 'personal-note-2b218.firebaseapp.com',
    storageBucket: 'personal-note-2b218.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUGkZ-bSMXTFv6pt21XnqUJmcNDwy3Yg',
    appId: '1:1054392847654:android:bc72e21aefeeec389285e7',
    messagingSenderId: '1054392847654',
    projectId: 'personal-note-2b218',
    storageBucket: 'personal-note-2b218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLI8Bp3ZQe8iiMjYPoDpaeXi9e8qYZ9E',
    appId: '1:1054392847654:ios:2d87fac2af08e1799285e7',
    messagingSenderId: '1054392847654',
    projectId: 'personal-note-2b218',
    storageBucket: 'personal-note-2b218.firebasestorage.app',
    iosBundleId: 'com.example.personalNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLI8Bp3ZQe8iiMjYPoDpaeXi9e8qYZ9E',
    appId: '1:1054392847654:ios:2d87fac2af08e1799285e7',
    messagingSenderId: '1054392847654',
    projectId: 'personal-note-2b218',
    storageBucket: 'personal-note-2b218.firebasestorage.app',
    iosBundleId: 'com.example.personalNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXmGLV9OkKNl4pMxIcNoxMNqsK0zk_4TU',
    appId: '1:1054392847654:web:bb2549788f2306989285e7',
    messagingSenderId: '1054392847654',
    projectId: 'personal-note-2b218',
    authDomain: 'personal-note-2b218.firebaseapp.com',
    storageBucket: 'personal-note-2b218.firebasestorage.app',
  );
}
